### ISSUE TITLE
rkevin's todo list

### ISSUE THREAD

**Issue by rkevin-arch** [Astrabit-ST/ModShot-Core#19]
Gonna plop an issue here to document the things we need to cleanup, as I go through everything and write documentation. Will be edited as I go.

- [x] Remove fiber binding, gamejolt binding, discord binding
- [ ] Find better way to deal with fibers that's serializable
- [x] Fix Linux build container not copying over data files anymore
- [x] Add a `dos2unix` command to the linux container so building from a repo cloned in windows would work (and remove the janky hack in conanfile after doing so
- [x] Make robocopy not overwrite build binaries on windows
- [x] Remove the `build-windows.yaml`, it's deprecated

Other things on my todo list:
- [x] Move windows binaries into `lib`, move `ssl` folder into lib
  - [x] Figure out a way to symlink `oneshot.exe` to `lib/oneshot.exe`
    - [x] Fix cwd issue
- [x] Finish up audio filters
  - [x] ~~Flush queued buffers when you add a non-OpenAL filter somehow~~ SCRAPPED
  - [x] Better API for ALEffects (figure out a way to reuse them without memory leaks / segfaults)
    - [x] Remove memory leaks
  - [x] Remove 3d audio disable thing in al-util.h
  - [x] Get filters working on SE
    - [x] And migrate the aux slot from alstream to audiostream, and make all sub alstreams attached to it
- [x] Better keyboard bindings
- [x] Remove need for linuxdeploy on linux? (manually set rpath to $ORIGIN, and save the time needed to strip stuff)
- [x] Documentation, documentation, documentation
- [x] Merge some patches into master once I'm done with audio filters
  - [x] `add-build-version`: version numbers
  - [x] `better-builds`: use everything-in-one-dir format instead of AppDir on linux, misc quality of life build workflow fixes
    - [x] Release `rkevin/build-oneshot-linux:1.2` and `rkevin/build-oneshot-windows:1.2` docker containers and retag existing ones
  - [x] `cleanup`: remove fiber, gamejolt, discord bindings
- [x] Fix that one compiler warning about non ISO compliant string arrays in binding-mri.cpp
- [x] Add F3 to close the game (when debug mode is on)

**Comment by rkevin-arch** [comment]
Most of the stuff on this list is done. Closing in favor of #32
