### ISSUE TITLE
TODO before ModShot's stable release

### ISSUE THREAD

**Issue by rkevin-arch** [Astrabit-ST/ModShot-Core#32]
Details in the word vomit over at https://github.com/Astrabit-ST/ModShot-Core/pull/31#issuecomment-803684008
- [ ] Figure out what to do with fiber support
- [ ] Profile the game and find out what's causing the performance issues with long vertical areas
- [x] Documentation, documentation, documentation
- [ ] Any feature requests from @Speak2Erase or @CryroFox that are suitable for upstream
