### ISSUE TITLE
rk's todo list v2

### ISSUE THREAD

**Issue by rkevin-arch** [Astrabit-ST/ModShot-Core#39]
- [ ] Valgrind build for ModShot
  - [ ] Debug audiochannel crashing issues (repro: `Audio.bgm_crossfade("Audio/BGM/Menderbot.ogg", 2, 100, 100)`
  - [x] #49
- [x] Add features to input module
  - [x] Set button for one frame
  - [x] Return currently pressed buttons
- [ ] Investigate #37 
- [x] #45
- [x] pain
